<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @return mixed
     */
    public function findActiveUsers()
    {
        /** @var EntityManager $em */
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('u')
            ->from('UserBundle:User', 'u')
            ->where('u.enabled = :enabled')
            ->setParameter('enabled', true)
            ->getQuery()
            ->getResult();

        return $query;
    }

    /**
     * @param User $user
     * @return mixed
     */
    public function findUserByIdAndToken(User $user, $token)
    {
        /** @var EntityManager $em */
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('u')
            ->addSelect('t')
            ->from('UserBundle:User', 'u')
            ->join('UserBundle:AccessToken', 't')
            ->where('u.id = :id')
            ->andWhere('t.user = :')
            ->andWhere('u.enabled = :enabled')
            ->setParameter('enabled', true)
            ->getQuery()
            ->getResult();

        return $query;
    }
}
